### ISSUE TITLE
[BUG] PyPy: breaking from a rich.progress.track loop doesn't work

### ISSUE THREAD

**Issue by Tyilo** [willmcgugan/rich#1037]
**Describe the bug**
When using PyPy exiting early from a `rich.progress.track` loop, doesn't terminate the live display used for the progress bar.

**To Reproduce**
Run the following code using PyPy:
```python
from rich.progress import track
for i in range(2):
    for j in track(range(1)):
        break
```

```
$ pypy3 --version
Python 3.7.9 (7e6e2bb30ac5fbdbd443619cae28c51d5c162a02, Nov 24 2020, 10:03:59)
[PyPy 7.3.3-beta0 with GCC 10.2.0]
$ pypy3 rich_bug.py
Traceback (most recent call last):
  File "rich_bug.py", line 5, in <module>
    for j in track(range(1)):
  File "/home/tyilo/.local/lib/python3.7/site-packages/rich/progress.py", line 145, in track
    with progress:
  File "/home/tyilo/.local/lib/python3.7/site-packages/rich/progress.py", line 640, in __enter__
    self.start()
  File "/home/tyilo/.local/lib/python3.7/site-packages/rich/progress.py", line 633, in start
    self.live.start(refresh=True)
  File "/home/tyilo/.local/lib/python3.7/site-packages/rich/live.py", line 108, in start
    self.console.set_live(self)
  File "/home/tyilo/.local/lib/python3.7/site-packages/rich/console.py", line 678, in set_live
    raise errors.LiveError("Only one live display may be active at once")
rich.errors.LiveError: Only one live display may be active at once
Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
```

**Platform**
Arch Linux using kitty terminal

**Diagnose**

```
$ pypy3 -m rich.diagnose
╭────────────────────────────────────────────────────────────── <class 'rich.console.Console'> ───────────────────────────────────────────────────────────────╮
│ A high level console interface.                                                                                                                             │
│                                                                                                                                                             │
│ ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=159 ColorSystem.TRUECOLOR>                                                                                                               │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                                                             │
│     color_system = 'truecolor'                                                                                                                              │
│         encoding = 'utf-8'                                                                                                                                  │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>                                                                            │
│           height = 71                                                                                                                                       │
│ is_dumb_terminal = False                                                                                                                                    │
│   is_interactive = True                                                                                                                                     │
│       is_jupyter = False                                                                                                                                    │
│      is_terminal = True                                                                                                                                     │
│   legacy_windows = False                                                                                                                                    │
│         no_color = False                                                                                                                                    │
│          options = ConsoleOptions(size=ConsoleDimensions(width=159, height=71), legacy_windows=False, min_width=1, max_width=159, is_terminal=True,         │
│                    encoding='utf-8', justify=None, overflow=None, no_wrap=False, highlight=None, height=None)                                               │
│            quiet = False                                                                                                                                    │
│           record = False                                                                                                                                    │
│         safe_box = True                                                                                                                                     │
│             size = ConsoleDimensions(width=159, height=71)                                                                                                  │
│        soft_wrap = False                                                                                                                                    │
│           stderr = False                                                                                                                                    │
│            style = None                                                                                                                                     │
│         tab_size = 8                                                                                                                                        │
│            width = 159                                                                                                                                      │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
$ pypy3 -mpip freeze | grep rich
rich==9.11.1
```

**Comment by willmcgugan** [comment]
That *should* work. It's fine in CPython. There's a context manager that should call `stop()` if the loop exits prematurely.

I suspect there is something different in how PyPy handles generators and context managers.

I'd suggest refactoring your inner loop to use a generator that yields values, and handle the break logic there. That may work around the issue.

**Comment by Ogeezle** [comment]
1qq1Sent from my Huawei phone

**Comment by Ogeezle** [comment]
Sent from my Huawei phone-------- Original message --------From: Will McGugan <notifications@github.com>Date: Sun, Feb 21, 2021, 9:57 PMTo: willmcgugan/rich <rich@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [willmcgugan/rich] [BUG] PyPy: breaking from a rich.progress.track loop doesn't work (#1037)
That should work. It's fine in CPython. There's a context manager that should call stop() if the loop exits prematurely.
I suspect there is something different in how PyPy handles generators and context managers.
I'd suggest refactoring your inner loop to use a generator that yields values, and handle the break logic there. That may work around the issue.

**Comment by willmcgugan** [comment]
Closing this because I suspect its a Pypy issue. Feel free to reopen if you have any more information.

**Comment by Tyilo** [comment]
This is due to a different behavior in PyPy: https://pypy.org/compat.html

> Similarly, remember that you must close() a non-exhausted generator in order to have its pending finally or with clauses executed immediately:

So the following works:

```python
from rich.progress import track
for i in range(2):
    g = track(range(1))
    for j in g:
        break
    g.close()
```
