### ISSUE TITLE
[BUG]Can't execute live_progress example in documentation

### ISSUE THREAD

**Issue by waynerv** [willmcgugan/rich#1105]
**Read the docs**
You might find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) -- consider using the search function there.

**Describe the bug**
Freeze when execute [live_progress.py](https://github.com/willmcgugan/rich/blob/master/examples/live_progress.py), After Ctrl+C raise a `rich.errors.NotRenderableError`.

**To Reproduce**
```
python live_progress.py

^CTraceback (most recent call last):
  File "live_progress.py", line 39, in <module>
    sleep(0.1)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "live_progress.py", line 45, in <module>
    overall_progress.update(overall_task, completed=completed)
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/live.py", line 190, in __exit__
    self.stop()
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/live.py", line 164, in stop
    self.refresh()
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/live.py", line 245, in refresh
    self.console.print(Control(""))
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/console.py", line 1226, in print
    extend(render(renderable, render_options))
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/console.py", line 893, in render
    for render_output in iter_render:
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/live.py", line 57, in __rich_console__
    lines = console.render_lines(self.renderable, options, pad=False)
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/console.py", line 925, in render_lines
    lines = list(
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/segment.py", line 184, in split_and_crop_lines
    for segment in segments:
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/console.py", line 893, in render
    for render_output in iter_render:
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/table.py", line 411, in __rich_console__
    widths = self._calculate_column_widths(console, max_width - extra_width)
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/table.py", line 445, in _calculate_column_widths
    width_ranges = [
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/table.py", line 446, in <listcomp>
    self._measure_column(console, column, max_width) for column in columns
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/table.py", line 631, in _measure_column
    _min, _max = get_render_width(console, cell.renderable, max_width)
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/measure.py", line 109, in get
    get_console_width(console, _max_width)
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/panel.py", line 172, in __rich_measure__
    measure_renderables(
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/measure.py", line 142, in measure_renderables
    measurements = [
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/measure.py", line 143, in <listcomp>
    get_measurement(console, renderable, max_width) for renderable in renderables
  File "/Users/waynerv/Repos/QData/qdatamgr-cli/venv/lib/python3.8/site-packages/rich/measure.py", line 119, in get
    raise errors.NotRenderableError(
rich.errors.NotRenderableError: Unable to get render width for <rich.progress.Progress object at 0x10f73bb20>; a str, Segment, or object with __rich_console__ method is required
```
**Platform**
MacOS 14 Iterm 2

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich

╭────────────────────────────────────────────────────── <class 'rich.console.Console'> ───────────────────────────────────────────────────────╮
│ A high level console interface.                                                                                                             │
│                                                                                                                                             │
│ ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=143 ColorSystem.TRUECOLOR>                                                                                               │ │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                                             │
│     color_system = 'truecolor'                                                                                                              │
│         encoding = 'utf-8'                                                                                                                  │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>                                                            │
│ is_dumb_terminal = False                                                                                                                    │
│       is_jupyter = False                                                                                                                    │
│      is_terminal = True                                                                                                                     │
│   legacy_windows = False                                                                                                                    │
│         no_color = False                                                                                                                    │
│          options = ConsoleOptions(legacy_windows=False, min_width=1, max_width=143, is_terminal=True, encoding='utf-8', justify=None,       │
│                    overflow=None, no_wrap=False, highlight=None)                                                                            │
│           record = False                                                                                                                    │
│         safe_box = True                                                                                                                     │
│             size = ConsoleDimensions(width=143, height=42)                                                                                  │
│        soft_wrap = False                                                                                                                    │
│           stderr = False                                                                                                                    │
│            style = None                                                                                                                     │
│         tab_size = 8                                                                                                                        │
│            width = 143                                                                                                                      │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)
rich==9.10.0
```

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by waynerv** [comment]
Fixed after upgrading rich to 9.13.0. Great!
