### ISSUE TITLE
[BUG] Error when printing output from network device

### ISSUE THREAD

**Issue by JulioPDX** [willmcgugan/rich#1157]
**Describe the bug**
Thank you for developing Rich! Amazing! Currently using Netmiko for SSH connections to networking devices. Before closing out the connection I will initiate a save command. The device outputs something like below:

```
Copying configuration: [\] 
Copying configuration: [|] 
Copying configuration: [/] 
Copying configuration: [-] 
Copying configuration: [\] 
Copying configuration: [|] 
Copying configuration: [/] 
```

**To Reproduce**

```python
from rich import print

mystring = """
Copying configuration: [\] 
Copying configuration: [|] 
Copying configuration: [/] 
Copying configuration: [-] 
Copying configuration: [\] 
Copying configuration: [|] 
Copying configuration: [/] 
"""

print(mystring)
```

## Traceback

```
Traceback (most recent call last):
  File "/home/juliopdx/git/multi-vendor-python/test.py", line 13, in <module>
    print(mystring)
  File "/home/juliopdx/git/myvenv/lib/python3.8/site-packages/rich/__init__.py", line 60, in print
    return write_console.print(*objects, sep=sep, end=end)
  File "/home/juliopdx/git/myvenv/lib/python3.8/site-packages/rich/console.py", line 1466, in print
    renderables = self._collect_renderables(
  File "/home/juliopdx/git/myvenv/lib/python3.8/site-packages/rich/console.py", line 1333, in _collect_renderables
    self.render_str(
  File "/home/juliopdx/git/myvenv/lib/python3.8/site-packages/rich/console.py", line 1224, in render_str
    rich_text = render_markup(text, style=style, emoji=emoji_enabled)
  File "/home/juliopdx/git/myvenv/lib/python3.8/site-packages/rich/markup.py", line 145, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/]' at position 80 has nothing to close
```

**Platform**
Ubuntu 18.04

**Diagnose**
`rich==10.0.1`

Thank you again!

**Comment by willmcgugan** [comment]
Glad you like Rich!

See the docs on [console markup](https://rich.readthedocs.io/en/latest/markup.html), which you may escape or disable.

**Comment by JulioPDX** [comment]
Thank you Will!
