### ISSUE TITLE
[BUG] examples/table_movie.py gives traceback

### ISSUE THREAD

**Issue by frosencrantz** [willmcgugan/rich#1204]
**Describe the bug**
`python examples/table_movie.py` gives a traceback:
```
Traceback (most recent call last):
  File "/home/git/rich/examples/table_movie.py", line 114, in <module>
    table_width = Measurement.get(console, table, console.width).maximum
  File "/usr/lib/python3.9/site-packages/rich/measure.py", line 95, in get
    _max_width = options.max_width
AttributeError: 'Table' object has no attribute 'max_width'
```

**To Reproduce**
```
python examples/table_movie.py
```

**Platform**
Linux.

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```
```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=149 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 47                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=149, height=47),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=149,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=149, height=47)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 149                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
platform="Linux"
WindowsConsoleFeatures(vt=False, truecolor=False)
rich @ file:///home/git/rich
```

**Did I help?**
I do not need this fixed, but you thought you would want to know.  I haven't actively used your software, but it looks  brilliant. Thanks for creating and sharing it.

**Comment by willmcgugan** [comment]
Thanks. There is a fix in master for this.
