### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arshadnzr** [willmcgugan/rich#1356]
**Describe the bug**
Rich Library doesnt seem to work on Google Cloud Instance

...
File "setup.py", line 4, in <module>
    from rich import print
  File "/home/nazir_arshad7/webserver-setup/rich/__init__.py", line 14
    _console: Optional["Console"] = None
            ^
SyntaxError: invalid syntax
...

**To Reproduce**
Make a gcp cloud instance
Operating System is Ubuntu 16
Install Rich 
try importing

**Platform**
Ubuntu 16

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
python -m rich.diagnose

Output . 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "rich/__init__.py", line 14
    _console: Optional["Console"] = None
            ^
SyntaxError: invalid syntax


python -m rich._windows

output : 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/usr/lib/python2.7/runpy.py", line 102, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "rich/__init__.py", line 14
    _console: Optional["Console"] = None
            ^
SyntaxError: invalid syntax

pip freeze | grep rich

You are using pip version 8.1.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
rich==10.6.0
```

*

**Comment by willmcgugan** [comment]
You’re running on Python 2.7. Rich requires 3.6.1 or above.

**Comment by arshadnzr** [comment]
> You’re running on Python 2.7. Rich requires 3.6.1 or above.

That was very simple problem , Sorry for disturbing and Thanks for the instant reply
