### ISSUE TITLE
[BUG] reconfiguring rich via pytest at runtime

### ISSUE THREAD

**Issue by neutrinoceros** [willmcgugan/rich#1425]
**Describe the bug**

Trying to reconfigure rich when my code is run via pytest, using the following pytest hook:

```python
# conftest.py

def pytest_configure():
    try:
        import rich
    except ImportError:
        pass
    else:
        rich.reconfigure(soft_wrap=False)
```

and invoking my tests with
```shell
pytest
```

I got the following error:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/robcleme/dev/my/wxc/tests/conftest.py", line 33, in pytest_configure
INTERNALERROR>     rich.reconfigure(soft_wrap=False)
INTERNALERROR>   File "/Users/robcleme/.pyenv/versions/wxc-dev/lib/python3.9/site-packages/rich/__init__.py", line 45, in reconfigure
INTERNALERROR>     _console.__dict__ = new_console.__dict__
INTERNALERROR> AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Platform**
OsX

**Diagnose**

```
python -m rich.diagnose
python -m rich._windows
pip freeze | grep rich
```
```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=185 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 52                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=185, height=52),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=185,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=52,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=185, height=52)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 185                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
platform="Darwin"
WindowsConsoleFeatures(vt=False, truecolor=False)
rich==10.7.0
```

**Comment by neutrinoceros** [comment]
while a possible patch on the rich side is proposed in #1426, a workaround this issue for existing versions of rich is to simply modify the pytest hook as:

```python


def pytest_configure():
    try:
        import rich
    except ImportError:
        pass
    else:
        rich.get_console()  # this is new !
        rich.reconfigure(soft_wrap=False)
```

**Comment by willmcgugan** [comment]
Yeah, this is a dup of https://github.com/willmcgugan/rich/issues/1407

Will have a fix in the next version.

I think you can work around it by calling `get_console()` prior to reconfigure.

**Comment by neutrinoceros** [comment]
Ah, sorry I missed #1407. Indeed this is the workaround I found too. Feel free to close this (and possibly my associated PR too if you have a better fix in mind).

**Comment by willmcgugan** [comment]
I suspect your fix is a good one. While track this in the other issue.

**Comment by neutrinoceros** [comment]
That being said my hook isn't solving the original problem I was having with my tests, I can't figure out why rich printing seems to be stuck on 70 cols even if I pass `width=200` instead (or in combination) of `soft_wrap=False` to `rich.reconfigure`
This causes my tests to fail because strings can't match their expect values, e.g.
```
E         - Error: type object 'pathlib.Path' has no attribute 'chmode'. Did you mean 'chmod' ?
E         ?                                                                           ---------
E         + Error: type object 'pathlib.Path' has no attribute 'chmode'. Did you mean
E         + 'chmod' ?
```
Is this a different bug (in which case I can open a new issue), or am I misunderstanding rich's docs somehow ?

**Comment by willmcgugan** [comment]
Do you have the env var COLUMNS set ?

**Comment by willmcgugan** [comment]
With regards to testing in general though. You may be better off working with Console objects explicitly. That way you have more control over the initial state.

Also, if you can, check the objects that are being printed, rather than the output. The output is subject to env vars and platform differences.

**Comment by neutrinoceros** [comment]
> Do you have the env var COLUMNS set ?

Ah, seems so. I can make my problem go away by setting _that_ in my pytest hook. Good call !

>With regards to testing in general though. You may be better off working with Console objects explicitly. That way you have more control over the initial state.

Sure. Right now I'm trying to live up to the spirit of my tweet https://twitter.com/neutrinoceros/status/1428812031524810756?s=20
This specific project is extremely small so I'd like to keep the technical debt close to zero, so I'll avoid using rich to the fullest for now :)

> Also, if you can, check the objects that are being printed, rather than the output. The output is subject to env vars and platform differences.

Well the output is really what I need to check, and rich is only an optional dependency at this point. But I'll keep this in mind for other projects where I'm integrating rich. Thanks !
