### ISSUE TITLE
[BUG] Dependency checks for pip-installed scripts

### ISSUE THREAD

**Issue by volundmush** [willmcgugan/rich#1709]
**Read the docs**
You might find a solution to your problem in the [docs](https://rich.readthedocs.io/en/latest/introduction.html) -- consider using the search function there.

**Describe the bug**
When running a Script installed via pip, Rich does not properly detect its dependencies. This specifically seems to affect Python versions 3.7 or higher. the "dataclasses" package is not available on higher versions of Python because it was added to the Python standard library, but the dependency check still is explicitly looking for that package. I get error messages talking about markers, and then when I try to run my mudforge command I get:

```
Traceback (most recent call last):
  File "/home/volund/pyenv/bin/mudforge", line 4, in <module>
    __import__('pkg_resources').require('mudforge==0.1.0')
  File "/home/volund/pyenv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/volund/pyenv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/volund/pyenv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/volund/pyenv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/volund/pyenv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/volund/pyenv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dataclasses<0.9,>=0.7; python_version < "3.7"' distribution was not found and is required by rich
```
This doesn't appear to actually affect rich's functionality. If I remove the dependeny check line in my virtualenv script file, everything works.

**To Reproduce**
Create a Python 3.10 Virtual Environment.
Activate said environment.

pip install git+git://github.com/volundmush/mudforge.git

run the command:
mudforge

**Platform**
Ubuntu 21.10

**Diagnose**
I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.

```
╭───────────────────────── <class 'rich.console.Console'> ─────────────────────────╮
│ A high level console interface.                                                  │
│                                                                                  │
│ ╭──────────────────────────────────────────────────────────────────────────────╮ │
│ │ <console width=194 ColorSystem.TRUECOLOR>                                    │ │
│ ╰──────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                  │
│     color_system = 'truecolor'                                                   │
│         encoding = 'utf-8'                                                       │
│             file = <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'> │
│           height = 24                                                            │
│    is_alt_screen = False                                                         │
│ is_dumb_terminal = False                                                         │
│   is_interactive = True                                                          │
│       is_jupyter = False                                                         │
│      is_terminal = True                                                          │
│   legacy_windows = False                                                         │
│         no_color = False                                                         │
│          options = ConsoleOptions(                                               │
│                        size=ConsoleDimensions(width=194, height=24),             │
│                        legacy_windows=False,                                     │
│                        min_width=1,                                              │
│                        max_width=194,                                            │
│                        is_terminal=True,                                         │
│                        encoding='utf-8',                                         │
│                        max_height=24,                                            │
│                        justify=None,                                             │
│                        overflow=None,                                            │
│                        no_wrap=False,                                            │
│                        highlight=None,                                           │
│                        markup=None,                                              │
│                        height=None                                               │
│                    )                                                             │
│            quiet = False                                                         │
│           record = False                                                         │
│         safe_box = True                                                          │
│             size = ConsoleDimensions(width=194, height=24)                       │
│        soft_wrap = False                                                         │
│           stderr = False                                                         │
│            style = None                                                          │
│         tab_size = 8                                                             │
│            width = 194                                                           │
╰──────────────────────────────────────────────────────────────────────────────────╯
```
rich==10.14.0

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/willmcgugan) my work on Rich, or [buy me a coffee](https://ko-fi.com/willmcgugan) to say thanks.

**Comment by willmcgugan** [comment]
The dataclasses packaged is installed conditionally (as you can see from `python_version < "3.7"`). This works fine here, so I suspect it is something to do with your environment. Try upgrading pip.
