### ISSUE TITLE
[BUG] can't format {task.speed} when customizing the progress bar

### ISSUE THREAD

**Issue by d0gkiller87** [willmcgugan/rich#1772]
**Describe the bug**

When customizing the progress bar, formatting `{task.speed}` would cause exceptions (e.g. `{task.speed:.0f}`).
When the task is just launched, `{task.speed}` is still `None`, which cannot be formatted.

**Reproduce steps**

```python3
from rich.progress import Progress

with Progress( "{task.speed:.0f}" ) as progress:
    for i in progress.track( range( 10 ) ):
        ...
```

Running the code above would throw the following exception:

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    for i in progress.track( range( 10 ) ):
  File "C:\Python38\lib\site-packages\rich\progress.py", line 695, in track
    task_id = self.add_task(description, total=task_total)
  File "C:\Python38\lib\site-packages\rich\progress.py", line 955, in add_task
    self.refresh()
  File "C:\Python38\lib\site-packages\rich\progress.py", line 866, in refresh
    self.live.refresh()
  File "C:\Python38\lib\site-packages\rich\live.py", line 213, in refresh
    self._live_render.set_renderable(self.renderable)
  File "C:\Python38\lib\site-packages\rich\live.py", line 195, in renderable
    renderable = self.get_renderable()
  File "C:\Python38\lib\site-packages\rich\live.py", line 98, in get_renderable
    self._get_renderable()
  File "C:\Python38\lib\site-packages\rich\progress.py", line 870, in get_renderable
    renderable = Group(*self.get_renderables())
  File "C:\Python38\lib\site-packages\rich\progress.py", line 875, in get_renderables
    table = self.make_tasks_table(self.tasks)
  File "C:\Python38\lib\site-packages\rich\progress.py", line 899, in make_tasks_table
    table.add_row(
  File "C:\Python38\lib\site-packages\rich\progress.py", line 902, in <genexpr>
    column.format(task=task)
TypeError: unsupported format string passed to NoneType.__format__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    ...
  File "C:\Python38\lib\site-packages\rich\progress.py", line 661, in __exit__
    self.stop()
  File "C:\Python38\lib\site-packages\rich\progress.py", line 647, in stop
    self.live.stop()
  File "C:\Python38\lib\site-packages\rich\live.py", line 142, in stop
    self.refresh()
  File "C:\Python38\lib\site-packages\rich\live.py", line 213, in refresh
    self._live_render.set_renderable(self.renderable)
  File "C:\Python38\lib\site-packages\rich\live.py", line 195, in renderable
    renderable = self.get_renderable()
  File "C:\Python38\lib\site-packages\rich\live.py", line 98, in get_renderable
    self._get_renderable()
  File "C:\Python38\lib\site-packages\rich\progress.py", line 870, in get_renderable
    renderable = Group(*self.get_renderables())
  File "C:\Python38\lib\site-packages\rich\progress.py", line 875, in get_renderables
    table = self.make_tasks_table(self.tasks)
  File "C:\Python38\lib\site-packages\rich\progress.py", line 899, in make_tasks_table
    table.add_row(
  File "C:\Python38\lib\site-packages\rich\progress.py", line 902, in <genexpr>
    column.format(task=task)
TypeError: unsupported format string passed to NoneType.__format__
```

**Platform**

`Windows 10 21H1` / `Windows Terminal` / `PowerShell 7.1.3` / `Python 3.8.5`

I may ask you to cut and paste the output of the following commands. It may save some time if you do it now.
```
python -m rich.diagnose
```
![image](https://user-images.githubusercontent.com/32069685/147228347-c2d0a2c0-7ba6-4e82-a00e-2af01ca6f740.png)

```
python -m rich._windows
```
```python3
platform="Windows"
WindowsConsoleFeatures(vt=True, truecolor=True)
```

```
pip freeze | grep rich
```
```python3
rich==10.16.1
```

**Comment by willmcgugan** [comment]
Speed is `None` because before you do any iterations there is no way for Rich to know the speed.

The solution depends on what you want to display, if you want to show speed 0, you could do `"{(task.speed or 0):.0f}"`.

If you want to do something else, you could create a custom column by extending `ProgressColumn`

**Comment by d0gkiller87** [comment]
My bad, didn't know you can use `or` in this expression. Thanks.

**Comment by d0gkiller87** [comment]
NVM, complex expressions such as `"{(task.speed)}"` are not supported.
```python3
from rich.progress import Progress

with Progress( "{(task.speed or 0):.0f}" ) as progress:
    for i in progress.track( range( 10 ) ):
        ...
```
```
Traceback (most recent call last):
  File ".\richtest.py", line 4, in <module>
    for i in progress.track( range( 10 ) ):
  File "C:\Python38\lib\site-packages\rich\progress.py", line 695, in track
    task_id = self.add_task(description, total=task_total)
  File "C:\Python38\lib\site-packages\rich\progress.py", line 955, in add_task
    self.refresh()
  File "C:\Python38\lib\site-packages\rich\progress.py", line 866, in refresh
    self.live.refresh()
  File "C:\Python38\lib\site-packages\rich\live.py", line 213, in refresh
    self._live_render.set_renderable(self.renderable)
  File "C:\Python38\lib\site-packages\rich\live.py", line 195, in renderable
    renderable = self.get_renderable()
  File "C:\Python38\lib\site-packages\rich\live.py", line 98, in get_renderable
    self._get_renderable()
  File "C:\Python38\lib\site-packages\rich\progress.py", line 870, in get_renderable
    renderable = Group(*self.get_renderables())
  File "C:\Python38\lib\site-packages\rich\progress.py", line 875, in get_renderables
    table = self.make_tasks_table(self.tasks)
  File "C:\Python38\lib\site-packages\rich\progress.py", line 899, in make_tasks_table
    table.add_row(
  File "C:\Python38\lib\site-packages\rich\progress.py", line 902, in <genexpr>
    column.format(task=task)
KeyError: '(task'
```

But I managed to solve it by extending the `ProgressColumn` class. Thanks for the advice.

```python3
from rich.progress import Progress, ProgressColumn
import time

class TaskSpeed( ProgressColumn ):
    def render( self, task ):
        return f"{( task.speed or 0 ):.1f}"

with Progress(
    TaskSpeed()
) as progress:
    for i in progress.track( range( 100 ) ):
        print( i )
        time.sleep( 0.1 )
```
