### ISSUE TITLE
Yaml syntax highlight fails

### ISSUE THREAD

**Issue by todoesverso** [willmcgugan/rich#21]
Trying to use `yaml` in syntaxt highlighting fails:

```python
from rich.console import Console
from rich.syntax import Syntax
console = Console()
code='''
yaml: true
'''
syntax = Syntax(code, 'yaml')
console.print(syntax)
```
```shell
$ python3 syntax.py 
Traceback (most recent call last):
  File "syntax.py", line 9, in <module>
    console.print(syntax)
  File "/home/todoesverso/.local/lib/python3.7/site-packages/rich/console.py", line 752, in print
    extend(render(renderable, render_options))
  File "/home/todoesverso/.local/lib/python3.7/site-packages/rich/console.py", line 520, in render
    yield from self._render(renderable, options)
  File "/home/todoesverso/.local/lib/python3.7/site-packages/rich/console.py", line 496, in _render
    for render_output in iter_render:
  File "/home/todoesverso/.local/lib/python3.7/site-packages/rich/syntax.py", line 209, in __console__
    text = self._highlight(self.lexer_name)
  File "/home/todoesverso/.local/lib/python3.7/site-packages/rich/syntax.py", line 156, in _highlight
    append(token, _get_theme_style(token_type))
  File "/home/todoesverso/.local/lib/python3.7/site-packages/rich/syntax.py", line 125, in _get_theme_style
    pygments_style = self._pygments_style_class.style_for_token(token_type)
  File "/home/todoesverso/.local/lib/python3.7/site-packages/pygments/style.py", line 128, in style_for_token
    t = cls._styles[token]
KeyError: Token.Literal.Scalar.Plain
```

**Comment by willmcgugan** [comment]
Please try Rich 0.7.2 on Pypi.

BTW you can do this:

```
python -m rich.syntax PATH
```

**Comment by todoesverso** [comment]
Niiiice! Working now!!! Thnaks!

![Screenshot from 2020-03-15 16-42-06](https://user-images.githubusercontent.com/45683/76709241-08851880-66dc-11ea-9ce1-7c0292fa5c80.png)
