### ISSUE TITLE
Progress: speed of 0 gets ZeroDivisionError

### ISSUE THREAD

**Issue by bphunter1972** [willmcgugan/rich#23]
```
In [9]: with Progress() as progress:
   ...:     a_task = progress.add_task("thing", total=41)
   ...:     progress.start()                             
   ...:     for cnt in range(41):                        
   ...:         time.sleep(.1)                           
   ...:         progress.update(a_task, 1)               
   ...:                                                  
thing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- Exception in thread Thread-704:
Traceback (most recent call last):                                                         
  File "/org/seg/tools/freeware/python/3.6.3/1/el-6-x86_64/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()                                                                                                       
  File "/home/bphunter/.cache/pypoetry/virtualenvs/icmerge-0gw-uTeS-py3.6/lib/python3.6/site-packages/rich/progress.py", line 289, in run
    self.progress.refresh()                                                                                                              
  File "/home/bphunter/.cache/pypoetry/virtualenvs/icmerge-0gw-uTeS-py3.6/lib/python3.6/site-packages/rich/progress.py", line 501, in refresh
    self._live_render.set_renderable(self._table)                                                                                            
  File "/home/bphunter/.cache/pypoetry/virtualenvs/icmerge-0gw-uTeS-py3.6/lib/python3.6/site-packages/rich/progress.py", line 521, in _table 
    widget = column(task)                                                                                                                    
  File "/home/bphunter/.cache/pypoetry/virtualenvs/icmerge-0gw-uTeS-py3.6/lib/python3.6/site-packages/rich/progress.py", line 107, in __call__
    renderable = self.render(task)                                                                                                            
  File "/home/bphunter/.cache/pypoetry/virtualenvs/icmerge-0gw-uTeS-py3.6/lib/python3.6/site-packages/rich/progress.py", line 136, in render  
    remaining = task.time_remaining                                                                                                           
  File "/home/bphunter/.cache/pypoetry/virtualenvs/icmerge-0gw-uTeS-py3.6/lib/python3.6/site-packages/rich/progress.py", line 270, in time_remaining
    estimate = ceil(self.remaining / speed)                                                                                                         
ZeroDivisionError: float division by zero                                                                                                           
```

**Comment by willmcgugan** [comment]
That is a bug (which I'll fix), but it is exposed by a misunderstanding of the API. The second [parameter to update](https://rich.readthedocs.io/en/latest/reference/progress.html#rich.progress.Progress.update) is a boolean to force a refresh. You probably want `progress.update(a_task, advance=1)` or `progress.advance(a_task, 1)`.

**Comment by willmcgugan** [comment]
btw `progress.start()` is called automatically if you use the context manager.

**Comment by willmcgugan** [comment]
Please try v0.8.2 in PyPi

**Comment by bphunter1972** [comment]
Thanks, Will, that seems to work. 
Somewhat confused by your comment about the second parameter to update. I'm calling advance() and giving it a float--how is that not correct?
Also, wouldn't it still possible for speed to be zero if total_completed is zero on line 258?

**Comment by willmcgugan** [comment]
You were calling `update()` in your example above with two positional arguments. The second argument was actually a boolean to force a refresh.. I've since made the arguments to `update()` keyword only to avoid that problem. Sounds like you are using `advance()` the way it was intended...

It was the `total_time` value being zero that cause the divide by zero. That's guarded by a condition above.

Feel free to close this if it is solved.

**Comment by bphunter1972** [comment]
Oh, my mistake! That example was a manufactured snippet from my App.
Thanks! Great work!
