### ISSUE TITLE
Can't print Table in a Gitlab CI runner

### ISSUE THREAD

**Issue by beojan** [willmcgugan/rich#68]
When running under a Gitlab CI runner, I get the following error when I print a `Table`:

```
Traceback (most recent call last):
  File ".ci/report.py", line 33, in <module>
    cons.print(table)
  File "/home/sftnight/.local/lib/python3.6/site-packages/rich/console.py", line 724, in print
    render(renderable, render_options), self.get_style(style)
  File "/home/sftnight/.local/lib/python3.6/site-packages/rich/console.py", line 347, in __exit__
    self._exit_buffer()
  File "/home/sftnight/.local/lib/python3.6/site-packages/rich/console.py", line 338, in _exit_buffer
    self._check_buffer()
  File "/home/sftnight/.local/lib/python3.6/site-packages/rich/console.py", line 804, in _check_buffer
    self.file.write(text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-50: ordinal not in range(128)
```

**Comment by willmcgugan** [comment]
Did you construct `cons` with a file argument at all?

If not, I would suspect a missing env var from the CI environment (LANG usually). You could try setting "PYTHONIOENCODING" env var to "UTF-8", which may fix it.

**Comment by beojan** [comment]
Setting `PYTHONIOENCODING="UTF-8"` worked, thanks.
