### ISSUE TITLE
My silly adventure to set up console with a theme with a hex color

### ISSUE THREAD

**Issue by chfw** [willmcgugan/rich#74]
Hi all,

Probably, my expectation was too high. I am playing with console theme and would like to set 'info' tag to a hex color so that, console.print('[info]information[/info]') would change according to the theme. Here is my brief journey before I could call console.print:

```
>>> from rich.color import parse_rgb_hex
>>> parse_rgb_hex('F47983')
ColorTriplet(red=244, green=121, blue=131)
>>> from rich.theme import Theme
>>> t = Theme({"info": "F47983"})
Traceback (most recent call last):
  File "/Users/jaska/github/moremoban/yehua-env/lib/python3.7/site-packages/rich/style.py", line 267, in parse
    Color.parse(word)
  File "/Users/jaska/github/moremoban/yehua-env/lib/python3.7/site-packages/rich/color.py", line 356, in parse
    raise ColorParseError(f"{color!r} is not a valid color")
rich.color.ColorParseError: 'f47983' is not a valid color

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaska/github/moremoban/yehua-env/lib/python3.7/site-packages/rich/theme.py", line 22, in __init__
    for name, style in styles.items()
  File "/Users/jaska/github/moremoban/yehua-env/lib/python3.7/site-packages/rich/theme.py", line 22, in <dictcomp>
    for name, style in styles.items()
  File "/Users/jaska/github/moremoban/yehua-env/lib/python3.7/site-packages/rich/style.py", line 270, in parse
    f"unable to parse {word!r} in style {style_definition!r}; {error}"
rich.errors.StyleSyntaxError: unable to parse 'f47983' in style 'F47983'; 'f47983' is not a valid color
>>> from rich.style import Style
>>> from rich.color import Color
>>> s = Style(color= Color.from_triplet(parse_rgb_hex('F47983')))
>>> t = Theme({"info": s})
>>> from rich.console import Console
>>> c=Console(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaska/github/moremoban/yehua-env/lib/python3.7/site-packages/rich/console.py", line 283, in __init__
    self._color_system = COLOR_SYSTEMS[color_system]
KeyError: <rich.theme.Theme object at 0x10bc19fd0>
```

Any way to go forward?

**Comment by willmcgugan** [comment]
RGB colors need a '#' prefix in a style definition ([docs](https://rich.readthedocs.io/en/latest/style.html))

Your first example should be:

```
t = Theme({"info": "#F47983"})
```

Similar issue with Style, there's no need to parse it first:

```
s = Style(color='#F47983')
```

**Comment by chfw** [comment]
Thanks for your hints but it still does not work
```
from rich.theme import Theme
from rich.console import Console

t = Theme({"info": '#F47983'})
c = Console(t)

c.print("[info]Hello[/info]")
```

```
Traceback (most recent call last):
  File "text.py", line 5, in <module>
    c = Console(t)
  File "/Users/jaska/.../rich/console.py", line 283, in __init__
    self._color_system = COLOR_SYSTEMS[color_system]
KeyError: <rich.theme.Theme object at 0x104d07198>
```

**Comment by willmcgugan** [comment]
Try this...

```python
c = Console(theme=t)
```

More on themes: https://rich.readthedocs.io/en/latest/style.html#style-themes
Console reference: https://rich.readthedocs.io/en/latest/reference/console.html

**Comment by chfw** [comment]
Wow! Finally:

<img width="46" alt="Screenshot 2020-05-15 at 22 49 29" src="https://user-images.githubusercontent.com/4280312/82099098-59c28000-96fe-11ea-8a4f-8f32ef691226.png">

```

from rich.theme import Theme
from rich.console import Console

t = Theme({"info": '#F47983'})
c = Console(theme=t)

c.print("[info]Hello[/info]")
```
