### ISSUE TITLE
rich.progress.Progress().add_task with total=0 gives ZeroDivisionError

### ISSUE THREAD

**Issue by efenka** [willmcgugan/rich#84]
If i create a progress bar with `total=0`
``` python3
from rich.progress import Progress

with Progress() as progress:
    bar_id = progress.add_task(total=0, description='Test')
```
or update it with such a total value
``` python3
from rich.progress import Progress

with Progress() as progress:
    bar_id = progress.add_task(description='Test')
    progress.update(bar_id, total=0)
```
i get a very deep traceback to a ZeroDivisionError:
``` python3
Traceback (most recent call last):━━━━━━━━━━━   0% -:--:--
  File "./test.py", line 6, in <module>
    progress.update(bar_id, total=0)
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 415, in __exit__
    self.stop()
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 397, in stop
    self.refresh()
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 542, in refresh
    self.console.print(self._live_render)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 710, in print
    extend(render(renderable, render_options))
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 504, in render
    yield from self._render(renderable, options)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 480, in _render
    for render_output in iter_render:
  File ".venv/lib/python3.8/site-packages/rich/live_render.py", line 28, in __console__
    lines = console.render_lines(self.renderable, options, style, pad=False)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 530, in render_lines
    lines = list(
  File ".venv/lib/python3.8/site-packages/rich/segment.py", line 72, in split_and_crop_lines
    for segment in segments:
  File ".venv/lib/python3.8/site-packages/rich/segment.py", line 46, in <genexpr>
    return (cls(text, apply(style)) for text, style in segments)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 504, in render
    yield from self._render(renderable, options)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 480, in _render
    for render_output in iter_render:
  File ".venv/lib/python3.8/site-packages/rich/table.py", line 324, in __console__
    yield from self._render(console, options, widths)
  File ".venv/lib/python3.8/site-packages/rich/table.py", line 485, in _render
    lines = console.render_lines(
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 530, in render_lines
    lines = list(
  File ".venv/lib/python3.8/site-packages/rich/segment.py", line 72, in split_and_crop_lines
    for segment in segments:
  File ".venv/lib/python3.8/site-packages/rich/segment.py", line 46, in <genexpr>
    return (cls(text, apply(style)) for text, style in segments)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 504, in render
    yield from self._render(renderable, options)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 480, in _render
    for render_output in iter_render:
  File ".venv/lib/python3.8/site-packages/rich/padding.py", line 83, in __console__
    lines = console.render_lines(self.renderable, child_options, style=style)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 530, in render_lines
    lines = list(
  File ".venv/lib/python3.8/site-packages/rich/segment.py", line 72, in split_and_crop_lines
    for segment in segments:
  File ".venv/lib/python3.8/site-packages/rich/segment.py", line 46, in <genexpr>
    return (cls(text, apply(style)) for text, style in segments)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 504, in render
    yield from self._render(renderable, options)
  File ".venv/lib/python3.8/site-packages/rich/console.py", line 480, in _render
    for render_output in iter_render:
  File ".venv/lib/python3.8/site-packages/rich/bar.py", line 63, in __console__
    complete_halves = int(width * 2 * completed / self.total)
ZeroDivisionError: division by zero
```

In my case this is because a http response content-length returned 0 and it's absolutely fine that rich cannot handle it, but the traceback I get is not very helpful. 

Please catch this situation earlier (in `progress.add_task` and `progress.update`) and either ignore it (because not setting total seems to be fine) or raise a more helpful Exception (like `ZeroDivisionError('invalid total value')`)

**Comment by willmcgugan** [comment]
It doesn't feel like an error per-se. More of a null operation. Only question is if `total` is 0, should the progress bar show 0% or 100% ?

**Comment by efenka** [comment]
Yeah, its more kind of unclear reporting. 

In my code I just check if the value I give is zero and skip the definition.
``` python3
total_size = …
if total_size:
    progress.update(bar_id, total=total_size)
```

This renders the progress bar with 100% what is fine.

**Comment by willmcgugan** [comment]
Please try with v1.1.7

**Comment by efenka** [comment]
Perfect, works great 👍.
