### ISSUE TITLE
Progress BarColumn with bar_width=None raises TypeError

### ISSUE THREAD

**Issue by efenka** [willmcgugan/rich#86]
I assume with the fix for #84 a new bug was introduced.

This code (note the `bar_width=None` to achieve 100% bar width) raises a TypeError in 1.1.7 and 1.1.8, but worked as expected (at leaset with positive total) in 1.1.6.

``` python3
from rich.progress import BarColumn
from rich.progress import Progress

with Progress(BarColumn(bar_width=None)) as progress:
    bar_id = progress.add_task(description='Test', total=100)
```

Gives me:
``` python3
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    bar_id = progress.add_task(description='Test', total=100)
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 440, in __exit__
    self.stop()
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 421, in stop
    self.refresh()
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 566, in refresh
    self._live_render.set_renderable(self.get_renderable())
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 575, in get_renderable
    renderable = RenderGroup(*self.get_renderables())
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 580, in get_renderables
    table = self.make_tasks_table(self.tasks)
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 607, in make_tasks_table
    widget = column(task)
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 109, in __call__
    renderable = self.render(task)
  File ".venv/lib/python3.8/site-packages/rich/progress.py", line 159, in render
    width=max(1, self.bar_width),
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by willmcgugan** [comment]
Yep. Please try v1.1.9

**Comment by efenka** [comment]
Great, also fixed now. Thanks a lot.
