### ISSUE TITLE
PyInstaller [BUG]

### ISSUE THREAD

**Issue by drain** [willmcgugan/rich#883]
### **Describe the bug**
Pyinstaller fails to run built executable using rich. 

Error:
```
Traceback (most recent call last):
  File "example.py", line 187, in <module>
  File "example.py", line 161, in display_running
  File "rich\live.py", line 116, in __init__
  File "rich\__init__.py", line 23, in get_console
ModuleNotFoundError: No module named 'rich.__init__.console'
[11512] Failed to execute script example
```

### **To Reproduce**
Build table_movie.py with PyInstaller and run it. 
Command used: `python37 -m PyInstaller example.py --onefile`

### **Platform**
Platform: Windows 10 64bit
Rich version: latest
Python version: 3.7.9

**Comment by willmcgugan** [comment]
Not an issue with Rich. Suggest you try the pyInstaller devs.
